# Book settings
title: CropEstStatsExt
author: World Bank Development Data Group
logo: docs/images/logo.png

repository:
    url: https://github.com/worldbank/CropEstStatsExt
    branch: main

html:
    home_page_in_navbar: false
    extra_navbar: ""
    use_edit_page_button: true
    use_repository_button: true
    use_issues_button: true
    baseurl: https://worldbank.github.io/CropEstStatsExt

only_build_toc_files: true